language: node_js

node_js:
  - '8.9.4'

cache:
  yarn: true
  directories:
    - node_modules

before_script:
- npm install -g bower
- bower install
- chmod +x ./deploy.sh

script:
  - bash ./deploy.sh